[env:lilygo-t-display]
platform = espressif32
board = lilygo-t-display
framework = arduino

lib_deps = 
    bodmer/TFT_eSPI
    bodmer/TFT_eWidget@^0.0.6

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_CS=2
    -D TFT_SCLK=25
    -D TFT_RST=-1
    -D TFT_DC=32
    -D LOAD_GLCD=1
    -D TFT_INVERSION_ON=1
    -D SPI_FREQUENCY=40000000

upload_speed = 115200
upload_flags =
    --before=default_reset
    --after=hard_reset
    
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
